from PySide6.QtWidgets import QWidget, QLabel, QGridLayout
from data_classes.model_info import ModelInfo
from helpers.list_model_widget import ListModelWidget

# TODO List
# 1. Create config files containing information about trained models - DONE
# 2. Add panel displaying models config files
# 3. Make files selectable
# 4. When selected display config and stats from images generated by yolo


class ViewModelsTab(QWidget):
    def __init__(self):
        super().__init__()
        self.layout = QGridLayout()
        self.config_list_widget = ListModelWidget("configs")  # Use modular widget
        self.details_label = QLabel("Select a config to view details")

        self.layout.addWidget(self.config_list_widget, 0, 0)
        self.layout.addWidget(self.details_label, 0, 1)
        self.setLayout(self.layout)

        self.config_list_widget.config_selected.connect(self.display_config_details)

    def display_config_details(self, config_name, config_data: ModelInfo):
        """Displays the selected config's details."""
        self.details_label.setText(f"<b>{config_name}</b><br><pre>{config_data.precision}</pre>")
