from PySide6.QtWidgets import QWidget, QVBoxLayout, QLabel

# TODO List
# 1. Create config files containing information about trained models
# 2. Add panel displaying models config files
# 3. Make files selectable
# 4. When selected display config and stats from images generated by yolo


class ViewModelsTab(QWidget):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout()
        layout.addWidget(QLabel("View Models"))
        layout.addWidget(QLabel(""))
        self.setLayout(layout)
